### PR TITLE
Adding support for specifying digest values in the container images.

### PR DESCRIPTION
**Pull request by mrglavas**
Resolves: https://github.com/kappnav/issues/issues/192

### CODE REVIEW

**Comment by mrglavas** [comment]
FYI, some of the lines got touched by vscode's auto-formatter. Can hide most of that when reviewing the PR by hiding whitespace changes.

**Comment by mrglavas** [comment]
The syntax is sha256:<value>. I suppose the operator could parse that and assume that anything starting with "sha256:" is a digest value, but that puts the burden on every consumer to do that and that includes authors of config maps. Think of a command action. You need to specify an image. If that value is coming from the kAppNav CR, you need to write more complicated code in the template language to compute the image value. I was going for more explicit typing than "magic".

**Comment by mrglavas** [comment]
Also not sure that `sha256:` is the only possible prefix for a digest value.

**Comment by mrglavas** [comment]
Also found: https://docs.docker.com/engine/reference/commandline/tag/ which states "A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.", so if we go the route of not adding an `isDigest` or type field, checking if the value contains a `:` might be sufficient.

**Comment by rlcundiff** [comment]
You're right, it does indicate that there may be other algorithms besides sha.  And given the definition of `digest := algorithm ":" hex"`it does look like we can key off of the colon.  Since this gives us a deterministic way to distinguish tag from digest, I'd much prefer to automatically detect which it is than have an additional element that seems redundant.

**Comment by mrglavas** [comment]
I warmed up a bit more to that idea over the weekend, but we should probably document it. Also need to confirm that the template language used for the config maps could process such a value.

**Comment by mrglavas** [comment]
@rlcundiff I've updated the PR based on our discussions. Go's template language has only a few bulit-in functions so I've added a bunch of string comparison functions that may be useful to a config map writer. Please review. Thanks.

**Pull request merged**
